services:
  tei:
    # No support for arm64 at this time
    platform: linux/amd64
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.2-grpc
    command:
      - --model-id=/srv/run/embedding-model
      - --port=8889
    ports:
      - "8889"
    restart: on-failure
    volumes:
      - ./.dist:/srv/run
  qdrant:
    # No support for arm64 at this time
    platform: linux/amd64
    image: ghcr.io/qdrant/qdrant/qdrant:v1.9.0-unprivileged
    command:
      - ./qdrant
      - --snapshot=/srv/run/embeddings.snapshot:main
    ports:
      - "6334"
    restart: on-failure
    volumes:
      - ./.dist:/srv/run
  server:
    build:
      context: ../../
    command:
      - server
      - --embed-address=tei:8889
      - --qdrant-address=qdrant:6334
      - --db-path=/srv/run/scores.db
    ports:
      - "8888:8888"
    restart: on-failure
    volumes:
      - ./.dist:/srv/run
